### ISSUE TITLE
mux: detector of route conflicts reports wrong handler file & line number

### ISSUE THREAD

**Issue by komuw** [komuw/ong#158]
The uris: `/post/create` and `"/post/:id"`

```go
mux := mux.New(
		l,
		middleware.WithOpts(domain, httpsPort, secretKey, l),
		nil,
		mux.NewRoute(
				"/post/create",
				mux.MethodAll,
				someHandler(),
			),
               mux.NewRoute(
				"/post/:id",
				mux.MethodAll,
				otherHandler(),
			),
	)
```

 are reported as;
```go
panic: 

You are trying to add
  pattern: /post/create
  method: ALL
  handler: github.com/komuw/ong/middleware.Panic.func1 - /home/user/gohack/github.com/komuw/ong/middleware/panic.go:17
However
  pattern: /post/:id
  method: ALL
  handler: github.com/komuw/ong/middleware.Panic.func1 - /home/user/gohack/github.com/komuw/ong/middleware/panic.go:17
already exists and would conflict.

goroutine 1 [running]:
github.com/komuw/ong/mux.(*router).detectConflict(0xc00013a4e0, {0x9c6bcf, 0x3}, {0xc000146210, 0x2b}, {0xa8ab00?, 0xc0000d75e0})
	/home/user/gohack/github.com/komuw/ong/mux/route.go:181 +0x7bc
github.com/komuw/ong/mux.(*router).handle(0xc00013a4e0, {0x9c6bcf, 0x3}, {0x9d8611, 0x2a}, 0xc0000d75e0)
	/home/user/gohack/github.com/komuw/ong/mux/route.go:100 +0x12d
github.com/komuw/ong/mux.Mux.addPattern(...)
	/home/user/gohack/github.com/komuw/ong/mux/mux.go:104
github.com/komuw/ong/mux.New({{0xa8a440, 0xc000130010}, 0xc000123470, {0xc00013c138, 0x16}, _, _, _}, {{0x9c86df, 0x9}, ...}, ...)
	/home/user/gohack/github.com/komuw/ong/mux/mux.go:86 +0x485
main.main()
	/home/user/mystuff/someProject/main.go:15 +0x356
exit status 2
```

Notice; `handler: github.com/komuw/ong/middleware.Panic.func1 - /home/user/gohack/github.com/komuw/ong/middleware/panic.go:17`     
If possible: that should actually point to the location of `someHandler` & `otherHandler` instead.

**Comment by komuw** [comment]
maybe call `runtime.stack()` and eliminate all lines that have the phrase; `komuw/ong` ?

**Comment by komuw** [comment]
```go
package main

import (
	"fmt"
	"net/http"
	"os"
	"reflect"
	"runtime"
	"strings"

	"github.com/komuw/ong/log"
	"github.com/komuw/ong/middleware"
)

func getfunc(handler interface{}) string {
	fn := runtime.FuncForPC(reflect.ValueOf(handler).Pointer())
	file, line := fn.FileLine(fn.Entry())
	return fmt.Sprintf("%s - %s:%d", fn.Name(), file, line)
}

func cool() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		_, _ = fmt.Fprintf(w, "hello %s.", "check")
	}
}

func main() {
	fmt.Println(
		getfunc(cool()),
	)

	fmt.Println(getfunc(
		middleware.All(
			cool(),
			middleware.WithOpts("localhost", 65081, "secretKey", log.New(os.Stdout, 1000)),
		),
	),
	)
}

// relevantCaller searches the call stack for the first function outside of net/http.
// The purpose of this function is to provide more helpful error messages.
func relevantCaller() runtime.Frame {
	// gotten from:
	// https://github.com/golang/go/blob/4a4127bccc826ebb6079af3252bc6bfeaec187c4/src/net/http/server.go#L1122
	pc := make([]uintptr, 16)
	n := runtime.Callers(1, pc)
	frames := runtime.CallersFrames(pc[:n])
	var frame runtime.Frame
	for {
		frame, more := frames.Next()
		fmt.Println("\n\t frame.Function: ", frame.Function)
		if !strings.HasPrefix(frame.Function, "github.com/komuw/ong") {
			fmt.Println("\n\t frame.Function 1: ", frame.Function)
			return frame
		}
		if !more {
			break
		}
	}

	// fmt.Println("\n\t frame.Function: ", frame.Function)
	return frame
}
```
`go run -race ./...`
```sh
main.cool.func1 - /home/komuw/mystuff/checkong/main.go:22
github.com/komuw/ong/middleware.Panic.func1 - /home/komuw/gohack/github.com/komuw/ong/middleware/panic.go:17
```
