### ISSUE TITLE
too many session cookies are been set

### ISSUE THREAD

**Issue by komuw** [komuw/ong#169]
`curl -vkIL https://localhost:65081/login`
```
HTTP/2 200 
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-site
ong-logid: KneYjkyeXjnqsjfYPfzk5A
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
set-cookie: Ong-logID=KneYjkyeXjnqsjfYPfzk5A; Path=/; Domain=localhost; Expires=Tue, 25 Oct 2022 12:11:33 GMT; Max-Age=900; HttpOnly; Secure; SameSite=Strict
set-cookie: csrftoken=uMVGht7HZE1yQ9snPDochmgprvLbP7dLNVabsUfs6DC_KeFOGEZMyToU7cyrQM8MqR3ytVz116o1IlUs0YtlUftg0bPzPw; Path=/; Domain=localhost; Expires=Tue, 25 Oct 2022 23:56:33 GMT; Max-Age=43200; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-kPlTqSpEFPZpZ0kB48I1WeCmNVum6UHLTDSGVhkhKG25_YItEjSVFGwbYkx_nEfI3SXgQizooNR6yW9yGh; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-mVC7rcg9mYlk7ytYxueQ4FZdZ5eo1L3wLRMI01gQ9Q9FQK9NkaQcnjFquxSwLgrzhm-HmOI1vrj9c5_UAu; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-muMQuGVyIKBAiXRKQjlDrKR-nqopQDE1iE6xL-t6M_BhYDeDHMtc0XJ13oZxLQ5Cx0S4UHFT-n1slpIqtm; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-kFIH8-htsdja7JjY-TTGjpsP3seGI3iuvPBjH_bjDEu-MggfMiPaGlHyoNhfJVhgrnZoXbtbZywvWz4G_N; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-lcJvXPdLqeV8m8mkZs0uhiijN7lkmQ0YB40c7zxnIfp6o-HiLiPpCuSiD2UPhLt638JpSQ07XPyywDIt8v; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-mHgmeX2GynxZPWQnYgJZ2ywMGP7ecTAsKh-jrwKUQ4aAjvAcIb6X59q8fvQ0LhLQGUWgggsVP1oLlTb8HI; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-lSU7VkTF70nCTnqwjLq6N5AIkYcjXJMO4tQ5FfV_m0bintxFn7tBPIugZlTVO-TQLUJKtf9aXfITXKNWHD; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-kuaS1OvEeEMQnKwC-Dg-MIrYcswYpY95JCluFuqA0iTC2_GlnO9iOGKTZ-agex-Amt3TrAKAEk5AzIntHE; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:hUwR2qiOU-nQsZmVWMRaA8L4opeusb5MD8oMaxr4HpPwnIEcoxm7F3tb7beJVcwIsKDQvo2vql6sDzW8d7j8rR7ITwY4; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:56:33 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
strict-transport-security: max-age=1296000; includeSubDomains; preload
vary: Origin
vary: Cookie
x-content-type-options: nosniff
x-csrf-token: uMVGht7HZE1yQ9snPDochmgprvLbP7dLNVabsUfs6DC_KeFOGEZMyToU7cyrQM8MqR3ytVz116o1IlUs0YtlUftg0bPzPw
x-frame-options: DENY
content-type: text/html; charset=utf-8
content-length: 832
date: Tue, 25 Oct 2022 11:56:33 GMT
```

**Comment by komuw** [comment]
strangely the other uris do not have the same issue:
`curl -vkIL https://localhost:65081/api`
```
HTTP/2 405 
content-type: text/plain; charset=utf-8
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-site
ong-logid: 3wtk97Kmz4j2sNXx3SrXsg
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
set-cookie: Ong-logID=3wtk97Kmz4j2sNXx3SrXsg; Path=/; Domain=localhost; Expires=Tue, 25 Oct 2022 13:28:04 GMT; Max-Age=900; HttpOnly; Secure; SameSite=Strict
set-cookie: csrftoken=u8_IrM5fO4A86T4jouQdfyboGkEY_8FfNadowJejwAA3aUXvmIEwC6jqiq9ac-4nHb6jdWVLHinaPoYdRVXVf-S3DDu4ag; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:13:04 GMT; Max-Age=43200; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:NYcohSObUVjk9ClT6n2HeCbUAFQYaZqDlK7AQMGYxCPBMwbAIg4noudnmFuOsCNCvoVtPUg6oJndxI-ftiX0xtw5Q_EW; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 03:13:04 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
strict-transport-security: max-age=1296000; includeSubDomains; preload
vary: Origin
vary: Cookie
x-content-type-options: nosniff
x-csrf-token: u8_IrM5fO4A86T4jouQdfyboGkEY_8FfNadowJejwAA3aUXvmIEwC6jqiq9ac-4nHb6jdWVLHinaPoYdRVXVf-S3DDu4ag
x-frame-options: DENY
content-length: 53
date: Tue, 25 Oct 2022 13:13:04 GMT
```

`curl -vkIL https://localhost:65081/check/89`
```
HTTP/2 200 
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-site
ong-logid: WMEGhw4jRXFWtqekxY4zkQ
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
set-cookie: Ong-logID=WMEGhw4jRXFWtqekxY4zkQ; Path=/; Domain=localhost; Expires=Tue, 25 Oct 2022 13:28:30 GMT; Max-Age=900; HttpOnly; Secure; SameSite=Strict
set-cookie: csrftoken=u8_IrM5fO4Cr0IQesiSxNxVHni4WH_VwB9xB8TXMq9BkKs9psI6hJsXaSoB_OGi2kfgAZzSAdybiC7hcaiipZIKX--I_5A; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:13:30 GMT; Max-Age=43200; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:NYcohSObUVhdZdPrfAJuk-EotBtSd7mCI2eFr7XFPdfqN0tH1ZVVHqa8CvzIUXa03sMwQcMcirKGsS58_2zvQLU1g1XASK5dZfpPXTvgLn04iE-xClU4a6wTkcaSCGmkB6GgD0P7y55FfGvL-b2LcJLUEIGLQSsBgw; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 03:13:30 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
strict-transport-security: max-age=1296000; includeSubDomains; preload
vary: Origin
vary: Cookie
x-content-type-options: nosniff
x-csrf-token: u8_IrM5fO4Cr0IQesiSxNxVHni4WH_VwB9xB8TXMq9BkKs9psI6hJsXaSoB_OGi2kfgAZzSAdybiC7hcaiipZIKX--I_5A
x-frame-options: DENY
content-type: text/plain; charset=utf-8
content-length: 22
date: Tue, 25 Oct 2022 13:13:30 GMT
```

**Comment by komuw** [comment]
repro
```go
l := log.New(os.Stdout, 1000)
	mux := mux.New(
		l,
		middleware.WithOpts("localhost", 65081, secretKey, l),
		nil,
		mux.NewRoute(
			"login",
			mux.MethodAll,
			login(),
		),
	)

func login() http.HandlerFunc {
	tmpl, err := template.New("myTpl").Parse(`<!DOCTYPE html>
<html>
<body>
	<h2>Welcome to awesome website.</h2>
	<form method="POST">
	<input type="text" id="email" name="email"><br>
	<input type="hidden" id="{{.CsrfTokenName}}" name="{{.CsrfTokenName}}" value="{{.CsrfTokenValue}}"><br>
	<input type="submit">
	</form>
</body>
</html>`)
	if err != nil {
		panic(err)
	}

	return func(w http.ResponseWriter, r *http.Request) {
		data := struct {
			CsrfTokenName  string
			CsrfTokenValue string
			CspNonceValue  string
		}{
			CsrfTokenName:  middleware.CsrfTokenFormName,
			CsrfTokenValue: middleware.GetCsrfToken(r.Context()),
			CspNonceValue:  middleware.GetCspNonce(r.Context()),
		}

		if err = tmpl.Execute(w, data); err != nil {
			panic(err)
		}
		return
	}
}
```

**Comment by komuw** [comment]
```go
func main() {
	l := log.New(os.Stdout, 1000)
	mux := mux.New(
		l,
		middleware.WithOpts("localhost", 65081, "hard-password", l),
		nil,
		mux.NewRoute(
			"login",
			mux.MethodAll,
			login(),
		),
	)

	err := server.Run(mux, server.DevOpts(), l)
	if err != nil {
		l.Error(err, log.F{"msg": "server.Run error"})
		os.Exit(1)
	}
}

func login() http.HandlerFunc {
	tmpl, err := template.New("myTpl").Parse(`<!DOCTYPE html>
<html>
<body>
  tokName="{{.CsrfTokenName}}" 
</body>
</html>`)
	if err != nil {
		panic(err)
	}

	return func(w http.ResponseWriter, r *http.Request) {
		data := struct{ CsrfTokenName string }{CsrfTokenName: middleware.CsrfTokenFormName}
		if err = tmpl.Execute(w, data); err != nil {
			panic(err)
		}
		return
	}
}
```
```sh
HTTP/2 200 
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-site
ong-logid: qTZXR35frR8Qn842sAWG2A
permissions-policy: interest-cohort=()
referrer-policy: strict-origin-when-cross-origin
set-cookie: Ong-logID=qTZXR35frR8Qn842sAWG2A; Path=/; Domain=localhost; Expires=Tue, 25 Oct 2022 14:10:19 GMT; Max-Age=900; HttpOnly; Secure; SameSite=Strict
set-cookie: csrftoken=zKmp2DL6ZnFqkh6KDIBK2-7wz1wJicrDgJW6lcoGb6T4u3ib39iICsWmAKlztKnINpSIbu-nDwlhE3jZCTJNRhceJW-78g; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 01:55:19 GMT; Max-Age=43200; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:JeajsmqZNyPiuOfRA--zl_dhmtIuQZ4ASiAym67Mg3keW_qLyUHeOmWMZ4KmJeY9b7UG54SEx6EXln6Em8cFsrrB6V0j; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 03:55:20 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:JeajsmqZNyPIZT3HlEbzYrDsnNVlfzfl6WbgJNTE06Gbv0Jg4y48d519Pc8BHR9yrGP4mL-wT7lpRVUa84C8x-Qd7Bcy; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 03:55:20 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
set-cookie: ong_sess=9:10:JeajsmqZNyOySZFwpPBiwaD1SRgYeH7VQtlhrjadrY2EHg6oXXJbnLEuyETH3NodfigWcbT9YC3dO90PrfdJYItwXJ1A; Path=/; Domain=localhost; Expires=Wed, 26 Oct 2022 03:55:20 GMT; Max-Age=50400; HttpOnly; Secure; SameSite=Strict
strict-transport-security: max-age=1296000; includeSubDomains; preload
```

The html template has to have `{{stuff}}` for the issue to reveal.

**Comment by komuw** [comment]
```diff
git diff sess/               

Δ sess/sess.go
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

──────────────────┐
• 5: package sess │
──────────────────┘
import (                                                                                    import (
    "context"                                                                                   "context"
    "encoding/json"                                                                             "encoding/json"
                                                                                                "fmt"
    "net/http"                                                                                  "net/http"
                                                                                                "runtime/debug"
    "time"                                                                                      "time"
                                                                                            
    "github.com/komuw/ong/cookie"                                                               "github.com/komuw/ong/cookie"

──────────────────┐
• 119: func Save( │
──────────────────┘
    mAge time.Duration,                                                                         mAge time.Duration,
    secretKey string,                                                                           secretKey string,
) {                                                                                         ) {
                                                                                                fmt.Println("\n\n ======================================== ")
                                                                                                debug.PrintStack()
                                                                                                fmt.Println("\n\n ======================================== ")
    ctx := r.Context()                                                                          ctx := r.Context()
    if vCtx := ctx.Value(ctxKey); vCtx != nil {                                                 if vCtx := ctx.Value(ctxKey); vCtx != nil {
        if s, ok := vCtx.(M); ok {                                                                  if s, ok := vCtx.(M); ok {
```

1. 
```go
goroutine 14 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/komuw/ong/sess.Save(0xc0000f4000, {0xbb9b38, 0xc002b24258}, {0xada97b, 0x9}, 0x0?, {0xadcd35, 0xd})
	/home/komuw/mystuff/ong/sess/sess.go:123 +0xcd
github.com/komuw/ong/middleware.(*sessRW).Write(0xc000142000, {0xc000032fc0, 0xa, 0x10})
	/home/komuw/mystuff/ong/middleware/session.go:79 +0xdf
text/template.(*state).walk(0xc000194f70, {0xa75e80?, 0xc000128000?, 0x431a70?}, {0xbbb9b8?, 0xc0000f7980})
	/usr/local/go/src/text/template/exec.go:281 +0x504
```

2.
```go
goroutine 14 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/komuw/ong/sess.Save(0xc0000f4000, {0xbb9b38, 0xc002b24258}, {0xada97b, 0x9}, 0xa52200?, {0xadcd35, 0xd})
	/home/komuw/mystuff/ong/sess/sess.go:123 +0xcd
github.com/komuw/ong/middleware.(*sessRW).Write(0xc000142000, {0xc0000716c0, 0x3, 0x70})
	/home/komuw/mystuff/ong/middleware/session.go:79 +0xdf
fmt.Fprint({0x7fc6ec787a98, 0xc000142000}, {0xc000194c88, 0x1, 0x1})
	/usr/local/go/src/fmt/print.go:243 +0x91
text/template.(*state).printValue(0xc000194f70, {0xbbb460?, 0xc0000f7a10}, {0xa52200?, 0xc0001280e0?, 0x5f865d?})
	/usr/local/go/src/text/template/exec.go:1018 +0x26e
```

3.
```go
goroutine 14 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/komuw/ong/sess.Save(0xc0000f4000, {0xbb9b38, 0xc002b24258}, {0xada97b, 0x9}, 0x0?, {0xadcd35, 0xd})
	/home/komuw/mystuff/ong/sess/sess.go:123 +0xcd
github.com/komuw/ong/middleware.(*sessRW).Write(0xc000142000, {0xc000032fd0, 0x9, 0x10})
	/home/komuw/mystuff/ong/middleware/session.go:79 +0xdf
text/template.(*state).walk(0xc000194f70, {0xa75e80?, 0xc000128000?, 0x431a70?}, {0xbbb9b8?, 0xc0000f7a40})
	/usr/local/go/src/text/template/exec.go:281 +0x504
text/template.(*state).walk(0xc000194f70, {0xa75e80?, 0xc000128000?, 0xc000194ef8?}, {0xbbb7c0?, 0xc0000f7950})
	/usr/local/go/src/text/template/exec.go:274 +0x727
```


So calling `tmpl.Execute(w, data)`; https://github.com/komuw/ong/blob/2306e7247a7101048cc0b1d4e1846d687b5834cc/example/main.go#L220-L222

calls `http.ResponseWriter.Write()`; https://github.com/komuw/ong/blob/2306e7247a7101048cc0b1d4e1846d687b5834cc/middleware/session.go#L71-L80

**Comment by komuw** [comment]
maybe we need to do what the gzip middleware does; https://github.com/komuw/ong/blob/2306e7247a7101048cc0b1d4e1846d687b5834cc/middleware/gzip.go#L48
